services:
  - type: web
    name: myapp
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: postgresql://sato_12345_app_2j06_user:tzwcXJUW8tX6yWWYe5d1zpcZJ18Ys2QR@dpg-cs7e3em8ii6s738uqqkg-a/sato_12345_app_2j06
        fromDatabase:
          name: myapp-db
          property: connectionString
      - key: f91526a9b6d0e0ffa17460e9f2303ccc
        sync: false

databases:
  - name: myapp-db
    databaseName: myapp
    user: myapp
